baseURL: 'https://Zii-yyE.github.io/'
languageCode: 'en-us'
title: '王子烨 Ziye Wang '
theme: 'papermod'

params:
  defaultTheme: auto 
  profileMode:
    enabled: true
    title: "Hi, I'm Ziye Wang"
    subtitle: "Undergraduate in Bioinformatics & Mathematics at Peking University"
    imageUrl: "/me.jpeg"      
    imageWidth: 180             
    imageHeight: 180             
    imageTitle: "My Avatar"
    buttons:
      - name: CV
        url: "/cv.pdf"

  socialIcons:
    - name: email
      url: "mailto:zzi_yye@stu.pku.edu.cn"
    - name: googlescholar
      url: "https://scholar.google.com/citations?user=your-google-scholar-id"
    - name: bluesky
      url: "https://bsky.app/profile/ziiyye.bsky.social"



markup:
  goldmark:
     renderer:
       unsafe: true
menu:
  main:
    - identifier: resources
      name: Resources
      url: /resources/
      weight: 1  
    - identifier: publications
      name: Publications
      url: /publications/
      weight: 2 


