baseURL: 'https://Zii-yyE.github.io/'
languageCode: 'en-us'
title: '王子烨 Ziye Wang '
theme: 'papermod'

markup:
  goldmark:
     renderer:
       unsafe: true
menu:
  main:
    - identifier: resources
      name: Resources
      url: /resources/
      weight: 1  
    - identifier: publications
      name: Publications
      url: /publications/
      weight: 2 
    - identifier: cv
      name: CV
      url: /cv/
      weight: 3 

